### ISSUE TITLE
Missing option to manage dbmodules section

### ISSUE THREAD

**Issue by marszip** [ccin2p3/puppet-mit_krb5#13]
In our situation we need the section dbmodules to be implemented. 
Is it possible to do this in the near future?

**Comment by riton** [comment]
This should not require too much work to add support for the `dbmodules` config section.
We'll try to implement that ASAP but we do not provide any guarantee to achieve this within the next two month.
If you really need this urgently, feel free to fork and submit a pull request. We'll be glad to merge this.

**Comment by marszip** [comment]
I was looking at the pull requests on the pfmooney repo. There is one pull request with the solution in there. Actually there are some issues fixed in pull requests that I need as well.
But there doesn't seem to be any merges in that repo. Especially the options mentioned in issues 9,10 and 11 are being used in our environment. 
```
Replace validate_string with data types  
 #14 opened on Feb 20 by vineetmadan    

Add support for canonicalize option present in mit_krb5 1.11+  
 #12 opened on May 8 2017 by dannygoulder    
 
Implement top-level include, includedir, module directives.  
 #11 opened on Nov 21 2016 by modax    

Implement dbmodules section.  
 #10 opened on Nov 21 2016 by modax    

Support kpasswd_server and master_kdc params for [realms].  
 #9 opened on Nov 21 2016 by modax   
```
I can try and make pull requests and transfer these solutions.

**Comment by riton** [comment]
`canonicalize` option has been merged recently (see 07fd55ab6182cb5fb960fd752f4739437bf1ecca) and is already available.

For the other, we'll be glad to merge if you port those. Thanks !

**Comment by riton** [comment]
If you go for a port of those merge requests, can you please submit different merge requests for each functionnality ? Thanks

**Comment by marszip** [comment]
I have ported three merge requests and made a pull request for each of them.

**Comment by marszip** [comment]
Can you have a look at these pull-requests and make a new release please? That would help me a lot.

**Comment by riton** [comment]
Version `1.0.0` has been released in the [Puppet Forge](https://forge.puppet.com/ccin2p3/mit_krb5/changelog#2018-09-05---remi-ferrand-puppetccin2p3fr---100) and includes all the patches you ported.
Thanks for the contribution !
