### ISSUE TITLE
hiera support

### ISSUE THREAD

**Issue by mxcheng2011** [ccin2p3/puppet-mit_krb5#20]
could you give an example to set up krb5.conf using hiera? I have problem setting up hiera yaml files for defined resource realm and domain_realm. Thank you!

**Comment by riton** [comment]
The `mit_krb5` module does not provide native support for what you'd like to do (If I understand well what you're trying to do).

Currently, the only way to achieve hiera integration as you'd like is to write some glue like

```puppet
$realms = lookup('site::krb5::realms', Hash)
create_resources('mit_krb5::realm', $realms)
```

This would be really easy to add support for such thing in this module, I'm gonna write it by the end of the week.

**Comment by riton** [comment]
[v1.1.0](https://forge.puppet.com/ccin2p3/mit_krb5/changelog#2018-09-20---remi-ferrand-puppetccin2p3fr---110) has been released and includes a [feature that should solve your issue](https://forge.puppet.com/ccin2p3/mit_krb5/readme#hiera-integration).

**Comment by mxcheng2011** [comment]
Remi, 

Thank you very much! realm and domain_realm work now with hiera. But it looks to me that appdefaults has some problem. For example

```
mit_krb5::appdefaults:
  'kinit':
    forwardable: true
```
gives me error message
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template mit_krb5/appdefaults.erb:
  Filepath: /etc/puppetlabs/code/environments/production/site/mit_krb5/templates/appdefaults.erb
  Line: 17
  Detail: undefined method `empty?' for true:TrueClass
```

**Comment by mxcheng2011** [comment]
Another problem is that `mit_krb5::default_ccache_name: 'KEYRING:persistent:%{uid}'` generates `default_ccache_name = KEYRING:persistent: `, where `%{uid}` is cut out. Do you know how to solve the problem?

**Comment by riton** [comment]
@mxcheng2011 to solve your last issue, here is the answer: https://puppet.com/docs/hiera/3.3/variables.html#the-literal-lookup-function

Try to write `'KEYRING:persistent:%{literal("%")}{uid}'` instead in your hiera data.

**Comment by riton** [comment]
#21 has been created to handle your other issue.

**Comment by mxcheng2011** [comment]
Remi, 

Thank you very much for the suggestions about literal lookup function. 

Mengxing
