### ISSUE TITLE
appdefaults does not accept boolean values

### ISSUE THREAD

**Issue by riton** [ccin2p3/puppet-mit_krb5#21]
Thank you very much! realm and domain_realm work now with hiera. But it looks to me that appdefaults has some problem. For example

```
mit_krb5::appdefaults:
  'kinit':
    forwardable: true
```
gives me error message
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template mit_krb5/appdefaults.erb:
  Filepath: /etc/puppetlabs/code/environments/production/site/mit_krb5/templates/appdefaults.erb
  Line: 17
  Detail: undefined method `empty?' for true:TrueClass
```

_Originally posted by @mxcheng2011 in https://github.com/ccin2p3/puppet-mit_krb5/issues/20#issuecomment-423251146_

**Comment by riton** [comment]
@mxcheng2011 release `v1.1.1` is out and fixes that problem.

**Comment by mxcheng2011** [comment]
Remi, thank you very much! mit_krb5::appdefaults works now.
