### ISSUE TITLE
Update of dependencies version

### ISSUE THREAD

**Issue by pyfontan** [ccin2p3/puppet-mit_krb5#3]
This module has been tested with : 
 - puppetlabs-concat (v1.1.1)
 - puppetlabs-stdlib (v4.4.0)

You can update metadata.json accordingly.

**Comment by riton** [comment]
Please provide a Pull-Request.

**Comment by faxm0dem** [comment]
PRs welcome @pyfontan

**Comment by riton** [comment]
Will be fixed in next release.
