### ISSUE TITLE
Fix legacy fact

### ISSUE THREAD

**Issue by flepoutre** [ccin2p3/puppet-mit_krb5#32]
Hello,
Is it possible to create new tag with legacy fact fix (please check the attachement) ?
Thanks.

Florent.
![Capture d’écran 2023-07-10 114155](https://github.com/ccin2p3/puppet-mit_krb5/assets/84913246/3aeadb3e-b2e8-460d-b703-ea0445b54b76)

**Comment by riton** [comment]
Will be included in the next release :heavy_check_mark:

**Comment by flepoutre** [comment]
Ok thanks.
Do you have any idea when the new release will be available ?
Thanks.
