### ISSUE TITLE
Update puppetlabs-concat version dependency

### ISSUE THREAD

**Issue by bschonec** [ccin2p3/puppet-mit_krb5#8]
Puppetlabs-concat v4.25.0 works perfectly fine for me on Puppet Open Source 5.3.

https://github.com/bschonec/puppet-mit_krb5/blob/f44a66ca0fbde477d72df63bcfd44da45c123b5c/metadata.json#L12

**Comment by bschonec** [comment]
This is a simple code change.  Can you take a look at this and give me an update?

**Comment by riton** [comment]
`puppetlabs-concat` _5.0.0_ has been successfully tested with this module. The `metadata.json` has been updated accordingly. I'm closing this issue.
